version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/acfs"
      - "/builds"
      - "/docker/convert"
      - "/streams"
      - "/sys/bytes"
      - "/sys/cgroup"
      - "/sys/crypto"
      - "/updater"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"