version: "2"
run:
  tests: true
  timeout: 5m
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gocritic
    - godoclint
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - modernize
    - nilerr
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
